// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpYsf-HtklLygAHK1zh7wggjU-Wgg5-U',
    appId: '1:1018341687243:web:023d69c09c5883e71bc04e',
    messagingSenderId: '1018341687243',
    projectId: 'flutter-application-12747',
    authDomain: 'flutter-application-12747.firebaseapp.com',
    storageBucket: 'flutter-application-12747.appspot.com',
    measurementId: 'G-KMB7MKTZSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvetLGsRoXgXkXOl_e2BwgKj4OwnQbIog',
    appId: '1:1018341687243:android:868047cb822746551bc04e',
    messagingSenderId: '1018341687243',
    projectId: 'flutter-application-12747',
    storageBucket: 'flutter-application-12747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbzhedOxe6nzyL-_ukikl9pLqlyiVSyU',
    appId: '1:1018341687243:ios:bc216a7314fa8fa41bc04e',
    messagingSenderId: '1018341687243',
    projectId: 'flutter-application-12747',
    storageBucket: 'flutter-application-12747.appspot.com',
    iosClientId: '1018341687243-lph0dh021sot3ufdhc50eogtjkoj4ofg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication.iphone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbzhedOxe6nzyL-_ukikl9pLqlyiVSyU',
    appId: '1:1018341687243:ios:4ce937df7d2890121bc04e',
    messagingSenderId: '1018341687243',
    projectId: 'flutter-application-12747',
    storageBucket: 'flutter-application-12747.appspot.com',
    iosClientId: '1018341687243-fgc5sv15gmv1v7rpmnfj8eumrrh0bo3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
